### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by karambaq** [Arthelon/imgclip#5]
`sudo imgclip image.png
/usr/local/lib/node_modules/imgclip/index.js:8
let print = false
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
`

**Comment by Arthelon** [comment]
@karambaq Seems like you're using a version of node that doesn't support es6 variable declarations. The cli only works with node v6.8.0+ as it is the only range of node versions supported by Tesseract, a core dependency of this project.
